
export const GET_PLAYCARD_START = "GET_PLAYCARD_START";
export const GET_PLAYCARD_SUCCESS = "GET_PLAYCARD_SUCCESS";
export const GET_PLAYCARD_ERROR = "GET_PLAYCARD_ERROR";


export const SEE_MORE_START="SEE_MORE_START";
export const SEE_MORE_SUCCESS="SEE_MORE_SUCCESS";
export const SEE_MORE_ERROR="SEE_MORE_ERROR"
 

export const GET_BOOKCARDS_START="GET_BOOKCARDS_START";
export const  GET_BOOKCARDS_SUCCESS="GET_BOOKCARDS_SUCCESS";
export const GET_BOOKCARDS_ERROR="GET_BOOKCARDS_ERROR";


export const GET_CARDINFO_START="GET_CARDINFO_START";
export const GET_CARDINFO_SUCCESS="GET_CARDINFO_SUCCESS";
export const GET_CARDINFO_ERROR="GET_CARDINFO_ERROR";